language: python
python:
  - "3.6"
install: # command to install dependencies
  - "pip install -r requirements.txt"
  - "pip install sh"
# command to run tests
script: py.test -s ./test.py
notifications:
  email:
    - sohrab.towfighi@mail.utoronto.ca
after_success:
  - coveralls